-- This file is for use with Corona Game Edition
-- 
-- The function getSpriteSheetData() returns a table suitable for importing using sprite.newSpriteSheetFromData()
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:e40ed122e017aea836457eee7f5309c6$
-- 
-- Usage example:
--        local sheetData = require "ThisFile.lua"
--        local data = sheetData.getSpriteSheetData()
--        local spriteSheet = sprite.newSpriteSheetFromData( "Untitled.png", data )
-- 
-- For more details, see http://developer.anscamobile.com/content/game-edition-sprite-sheets

local SpriteSheet = {}
SpriteSheet.getSpriteSheetData = function ()
	return {
		frames = {
			{
				name = "snake1.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 250 },
				textureRect = { x = 0, y = 0, width = 100, height = 250 },
				spriteSourceSize = { width = 100, height = 250 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "snake2.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 250 },
				textureRect = { x = 100, y = 0, width = 100, height = 250 },
				spriteSourceSize = { width = 100, height = 250 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "snake3.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 250 },
				textureRect = { x = 200, y = 0, width = 100, height = 250 },
				spriteSourceSize = { width = 100, height = 250 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "snake4.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 250 },
				textureRect = { x = 300, y = 0, width = 100, height = 250 },
				spriteSourceSize = { width = 100, height = 250 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "snake5.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 250 },
				textureRect = { x = 400, y = 0, width = 100, height = 250 },
				spriteSourceSize = { width = 100, height = 250 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "snake6.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 250 },
				textureRect = { x = 0, y = 250, width = 100, height = 250 },
				spriteSourceSize = { width = 100, height = 250 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "snake7.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 250 },
				textureRect = { x = 100, y = 250, width = 100, height = 250 },
				spriteSourceSize = { width = 100, height = 250 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "snake8.png",
				spriteColorRect = { x = 0, y = 0, width = 100, height = 250 },
				textureRect = { x = 200, y = 250, width = 100, height = 250 },
				spriteSourceSize = { width = 100, height = 250 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}
end
return SpriteSheet

